import { test, expect, type Page, type APIRequestContext } from '@playwright/test'
import { randomUUID } from 'node:crypto'
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1cAAAAASUVORK5CYII=', 'base64')
async function login(page: Page, name = 'user', password = name) {
  await page.goto('/login'); await page.getByLabel('아이디 또는 이메일').fill(name); await page.getByLabel('비밀번호', { exact: true }).fill(password)
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: name === 'seller' ? '상품 관리' : '내 계정', exact: true })).toBeVisible()
}
async function bearer(request: APIRequestContext, account = 'seller') {
  const response = await request.post('/api/member/v1/auth/login', { data: { email: account + '@local.test', password: account } }); expect(response.ok()).toBeTruthy()
  return { Authorization: 'Bearer ' + (await response.json()).data.accessToken }
}
async function fixture(request: APIRequestContext) {
  const headers = await bearer(request)
  const image = await request.post('/api/shopping/v1/admin/product-images', { headers, multipart: { file: { name: 'fixture.png', mimeType: 'image/png', buffer: png } } }); expect(image.ok()).toBeTruthy()
  const name = 'E2E 상품 ' + randomUUID().slice(0, 8)
  const created = await request.post('/api/shopping/v1/admin/products', { headers: { ...headers, 'X-Idempotency-Key': randomUUID() }, data: { name, description: '실제 kind API 테스트 상품', mainImageId: (await image.json()).data.imageId } }); expect(created.ok()).toBeTruthy()
  const productId = String((await created.json()).data.productId)
  const sale = await request.post('/api/commerce/v1/sales', { headers, data: { productId: Number(productId), price: 10000, initialStock: 20 } }); expect(sale.ok()).toBeTruthy()
  const salesId = (await sale.json()).id
  expect((await request.patch(`/api/commerce/v1/sales/${salesId}/status`, { headers, data: { status: 'ON_SALE' } })).ok()).toBeTruthy()
  return { productId, name, headers, salesId }
}
test('kind: seller product upload, JSON register, sale configuration and atomic stock delta', async ({ page }) => {
  const name = '판매자 화면 ' + randomUUID().slice(0, 8)
  await login(page, 'seller'); await page.getByRole('link', { name: '상품 등록', exact: true }).click()
  await page.getByLabel('상품명', { exact: true }).fill(name); await page.getByLabel('상품 설명', { exact: true }).fill('프론트 연동 확인')
  await page.locator('input[type=file]').setInputFiles({ name: 'product.png', mimeType: 'image/png', buffer: png })
  await page.getByRole('button', { name: '기본정보 등록', exact: true }).click()
  await expect(page.getByRole('heading', { name: '상품 수정', exact: true })).toBeVisible()
  await page.getByLabel('판매 가격(원)', { exact: true }).fill('12000'); await page.getByLabel('최초 재고(개)', { exact: true }).fill('8')
  await page.getByRole('button', { name: '판매 설정 저장', exact: true }).click(); await expect(page.getByRole('button', { name: '판매 시작', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '판매 시작', exact: true }).click(); await expect(page.getByRole('button', { name: '비공개로 전환' })).toBeVisible()
  await page.getByLabel(/재고 증감량/).fill('-2'); await page.getByRole('button', { name: '재고 수정', exact: true }).click()
  await expect(page.getByLabel('재고 증감량(개) — 현재 6', { exact: true })).toBeVisible()
  await page.getByLabel(/판매 가격\(원\) — 현재/).fill('13000'); await page.getByRole('button', { name: '가격 변경', exact: true }).click()
  await expect(page.getByLabel(/판매 가격.*13,000/)).toBeVisible()
  await page.getByLabel('상품 설명', { exact: true }).fill('수정한 상품 설명')
  await page.getByRole('button', { name: '기본정보 저장', exact: true }).click(); await expect(page.getByText('기본정보를 저장했어요.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '비공개로 전환' }).click(); await expect(page.getByRole('button', { name: '공개 재개', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '공개 재개', exact: true }).click(); await expect(page.getByRole('button', { name: '비공개로 전환' })).toBeVisible()
  await page.getByRole('link', { name: '공개 상세 보기' }).click(); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-artifacts/kind-product-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 }); await expect(page.getByRole('link', { name: '바로 구매', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-artifacts/kind-product-mobile.png', fullPage: true })
})
test('kind: member cart update, selected-item order, payment polling and own history', async ({ page, request }) => {
  const { productId, name } = await fixture(request)
  const other = await fixture(request)
  expect((await request.post('/api/commerce/v1/cart/items', { headers: await bearer(request, 'user'), data: { productId: Number(other.productId), quantity: 1 } })).ok()).toBeTruthy()
  await login(page); await page.getByRole('link', { name: '쇼핑', exact: true }).click()
  await page.getByRole('link', { name: new RegExp(name) }).first().click()
  await page.getByRole('button', { name: '장바구니 담기', exact: true }).click(); await expect(page.getByText('장바구니에 담았어요.', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '장바구니', exact: true }).click()
  const row = page.locator('section').filter({ has: page.getByRole('heading', { name, exact: true }) })
  const otherRow = page.locator('section').filter({ has: page.getByRole('heading', { name: other.name, exact: true }) })
  const total = page.getByRole('region', { name: '장바구니 합계' }).locator('strong')
  await expect(row.getByLabel('상품 금액')).toHaveText('10,000원')
  await expect(otherRow.getByLabel('상품 금액')).toHaveText('10,000원')
  const initialTotal = Number((await total.innerText()).replace(/[^0-9]/g, ''))
  expect((await request.patch(`/api/commerce/v1/sales/${other.salesId}/price`, { headers: other.headers, data: { price: 11000 } })).ok()).toBeTruthy()
  await expect(row.getByRole('button', { name: '수량 줄이기' })).toBeDisabled()
  await expect(row.getByRole('button', { name: '수량 저장' })).toHaveCount(0)
  const refreshed = page.waitForResponse(response => response.url().endsWith('/api/commerce/v1/cart/items') && response.request().method() === 'GET')
  await row.getByRole('button', { name: '수량 늘리기' }).click(); await refreshed
  await expect(row.locator('output')).toHaveText('2')
  await expect(row.getByLabel('상품 금액')).toHaveText('20,000원')
  await expect(otherRow.getByLabel('상품 금액')).toHaveText('11,000원')
  await expect(total).toHaveText((initialTotal + 11000).toLocaleString('ko-KR') + '원')
  await expect(row.getByRole('button', { name: '수량 줄이기' })).toBeEnabled()
  await row.getByRole('button', { name: '수량 줄이기' }).click(); await expect(row.locator('output')).toHaveText('1')
  await expect(row.getByLabel('상품 금액')).toHaveText('10,000원')
  await expect(total).toHaveText((initialTotal + 1000).toLocaleString('ko-KR') + '원')
  await expect(row.getByRole('button', { name: '수량 줄이기' })).toBeDisabled()
  await row.getByRole('button', { name: '수량 늘리기' }).click(); await expect(row.locator('output')).toHaveText('2')
  await page.screenshot({ path: 'test-artifacts/kind-cart-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-artifacts/kind-cart-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 720 })
  await otherRow.getByRole('button', { name: '삭제', exact: true }).click()
  await expect(otherRow).toHaveCount(0)
  await expect(total).toHaveText(initialTotal.toLocaleString('ko-KR') + '원')
  await page.getByLabel('전체 선택', { exact: true }).uncheck(); await page.getByLabel(name + ' 선택', { exact: true }).check()
  await page.getByRole('link', { name: '선택 상품 주문', exact: true }).click(); await expect(page.getByRole('heading', { name: '선택 상품 주문서', exact: true })).toBeVisible()
  await page.getByLabel('연락처', { exact: true }).fill('010-1234-5678'); await page.getByLabel('상품별 주문과 통합 결제 금액을 확인했습니다').check()
  await page.getByRole('button', { name: '통합 주문 만들기', exact: true }).click()
  await expect(page.getByRole('heading', { name: '통합 결제', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '통합 결제하기', exact: true }).click()
  await expect(page.getByText('통합 결제가 완료되었어요', { exact: true })).toBeVisible({ timeout: 30000 })
  const groupNumber = decodeURIComponent(new URL(page.url()).pathname.split('/').pop()!)
  const token = await bearer(request, 'user')
  const groupResponse = await request.get(`/api/commerce/v1/payment-groups/${encodeURIComponent(groupNumber)}`, { headers: token }); expect(groupResponse.ok()).toBeTruthy()
  const group = await groupResponse.json(); const orderNumber = group.orders.find((o: { productName: string }) => o.productName === name).orderNumber
  const saved = await request.get(`/api/commerce/v1/orders/${encodeURIComponent(orderNumber)}`, { headers: token }); expect(saved.ok()).toBeTruthy()
  const order = await saved.json(); expect(order.quantity).toBe(2); expect(order.totalAmount).toBe(20000); expect(order.status).toBe('PAID')
  const cart = await request.get('/api/commerce/v1/cart/items', { headers: token }); expect((await cart.json()).some((item: { productId: number }) => item.productId === Number(productId))).toBeFalsy()
  await page.getByRole('link', { name: '내 주문 목록', exact: true }).click(); await expect(page.getByRole('link', { name, exact: true })).toBeVisible()
})
test('kind: direct order, pending cancellation and member ownership', async ({ page, request }) => {
  const f = await fixture(request); const headers = await bearer(request, 'user')
  const response = await request.post('/api/commerce/v1/orders', { headers: { ...headers, 'X-Idempotency-Key': randomUUID() }, data: { productId: Number(f.productId), quantity: 1, buyerName: '유저', buyerPhone: '01012345678', expectedTotalAmount: 10000 } }); expect(response.ok()).toBeTruthy()
  const pending = await response.json()
  const unauthorized = await request.get(`/api/commerce/v1/orders/${pending.orderNumber}`, { headers: f.headers }); expect(unauthorized.status()).toBe(404)
  await login(page); await page.getByRole('link', { name: '내 주문', exact: true }).first().click()
  await page.getByRole('link', { name: f.name, exact: true }).click()
  await page.getByRole('link', { name: '통합 결제 확인', exact: true }).click()
  await page.getByRole('button', { name: '전체 주문 취소', exact: true }).click(); await expect(page.getByText('주문이 취소되었어요', { exact: true })).toBeVisible()
  const saved = await request.get(`/api/commerce/v1/orders/${pending.orderNumber}`, { headers }); expect((await saved.json()).status).toBe('CANCELLED')
})
test('kind: seller Live link/reorder/unlink, SSE chat/likes and end disable participation', async ({ page, request, browser }) => {
  const f = await fixture(request); const f2 = await fixture(request); const title = '연동 방송 ' + randomUUID().slice(0, 8)
  const channelId = randomUUID().slice(0, 8)
  await login(page, 'seller'); await page.getByRole('link', { name: '방송 관리', exact: true }).click(); await page.getByRole('link', { name: '방송 등록', exact: true }).click()
  await page.getByLabel('방송 제목', { exact: true }).fill(title)
  await page.getByLabel('AWS IVS 채널 ARN', { exact: true }).fill('arn:aws:ivs:ap-northeast-2:123456789012:channel/' + channelId)
  await page.getByLabel('예정 시작 시각', { exact: true }).fill('2026-10-06T18:00')
  await page.getByLabel('AWS IVS 시청 연결 정보', { exact: true }).fill('https://stub.live-video.net/' + channelId + '.m3u8')
  await page.getByRole('button', { name: '방송 등록', exact: true }).click(); await expect(page.getByRole('heading', { name: '방송 편집' })).toBeVisible()
  const liveId = new URL(page.url()).pathname.split('/').pop()!
  await page.getByLabel('방송 제목', { exact: true }).fill(title + ' 수정')
  await page.getByRole('button', { name: '기본정보 저장', exact: true }).click(); await expect(page.getByText('방송 기본정보를 저장했어요.', { exact: true })).toBeVisible()
  const select = page.getByRole('combobox', { name: '연결할 상품' })
  await select.selectOption(f.productId); await page.getByRole('button', { name: '상품 연결', exact: true }).click()
  await expect(page.getByRole('button', { name: f.name + ' 아래로', exact: true })).toBeVisible()
  await select.selectOption(f2.productId); await page.getByRole('button', { name: '상품 연결', exact: true }).click()
  await expect(page.getByRole('button', { name: f.name + ' 아래로', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: f.name + ' 아래로', exact: true }).click()
  await expect(page.getByText('노출 순서를 저장했어요.', { exact: true })).toBeVisible()
  const links = await request.get(`/api/live/v1/admin/broadcasts/${liveId}/products`, { headers: f.headers })
  expect(String((await links.json()).data[0].productId)).toBe(f2.productId)
  const secondRow = page.locator('[class*=linked]').filter({ hasText: f2.name }).filter({ has: page.getByRole('button', { name: '해제', exact: true }) }).last()
  await secondRow.getByRole('button', { name: '해제', exact: true }).click()
  await expect(page.getByRole('button', { name: f2.name + ' 아래로', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '방송 시작', exact: true }).click(); await expect(page.getByRole('button', { name: '방송 종료', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '해제', exact: true })).toBeDisabled()
  const viewerContext = await browser.newContext(); const viewer = await viewerContext.newPage()
  await viewer.goto(`http://127.0.0.1:5174/lives/${liveId}`)
  await viewer.getByRole('tab', { name: '채팅', exact: true }).click(); await expect(viewer.getByRole('button', { name: '좋아요 보내기' })).toBeDisabled()
  await expect(viewer.getByText('최근 50개 채팅 · 실시간 연결됨', { exact: true })).toBeVisible()
  const user = await bearer(request, 'user')
  const sent = await request.post(`/api/live/v1/broadcasts/${liveId}/chats`, { headers: user, data: { content: '익명 시청자도 채팅을 조회합니다' } }); expect(sent.ok()).toBeTruthy()
  await expect(viewer.getByText('익명 시청자도 채팅을 조회합니다', { exact: true })).toBeVisible()
  await viewer.getByRole('link', { name: '로그인하고 참여하기' }).click()
  await viewer.getByLabel('아이디 또는 이메일').fill('user'); await viewer.getByLabel('비밀번호', { exact: true }).fill('user'); await viewer.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(viewer.getByRole('heading', { name: title + ' 수정', exact: true })).toBeVisible()
  await viewer.getByRole('tab', { name: '채팅', exact: true }).click(); await viewer.getByLabel('채팅 입력').fill('프론트에서 전송한 채팅')
  await viewer.getByRole('button', { name: '전송', exact: true }).click(); await expect(viewer.getByText('프론트에서 전송한 채팅', { exact: true })).toBeVisible()
  await viewer.getByRole('button', { name: '좋아요 보내기' }).click(); await expect(viewer.getByText('좋아요 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '방송 종료', exact: true }).click(); await page.getByRole('button', { name: '종료 확정', exact: true }).click()
  await expect(viewer.getByText('방송이 종료되었어요', { exact: true })).toBeVisible()
  await expect(viewer.getByRole('button', { name: '전송', exact: true })).toBeDisabled(); await expect(viewer.getByRole('button', { name: '좋아요 취소', exact: true })).toBeDisabled()
  await viewer.screenshot({ path: 'test-artifacts/kind-live-chat.png', fullPage: true }); await viewerContext.close()
})
test('kind: signup, profile edit and withdrawal', async ({ page }) => {
  const email = 'e2e-' + randomUUID() + '@local.test'; const password = 'TestPassword123!'
  await page.goto('/signup'); await page.getByLabel('이메일', { exact: true }).fill(email); await page.getByLabel('비밀번호', { exact: true }).fill(password); await page.getByLabel('이름', { exact: true }).fill('E2E 회원')
  await page.getByRole('button', { name: '가입하기', exact: true }).click(); await expect(page.getByRole('heading', { name: '로그인', exact: true })).toBeVisible()
  await login(page, email, password)
  await page.getByLabel('변경할 이름').fill('변경된 회원'); await page.getByRole('button', { name: '이름 저장' }).click(); await expect(page.getByText('변경된 회원', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '회원 탈퇴', exact: true }).click(); await page.getByLabel('현재 비밀번호').fill(password); await page.getByRole('button', { name: '탈퇴 확정' }).click()
  await expect(page.getByRole('link', { name: '로그인', exact: true })).toBeVisible()
})

test('kind: frontend direct purchase creates the quoted order and completes payment', async ({ page, request }) => {
  const f = await fixture(request)
  await page.goto(`/products/${f.productId}`)
  await page.getByRole('link', { name: '바로 구매', exact: true }).click()
  await expect(page.getByRole('heading', { name: '로그인', exact: true })).toBeVisible()
  await page.getByLabel('아이디 또는 이메일').fill('user'); await page.getByLabel('비밀번호', { exact: true }).fill('user')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '주문서', exact: true })).toBeVisible()
  await page.getByLabel('연락처', { exact: true }).fill('01012345678'); await page.getByLabel('주문 내용을 확인했으며 결제에 동의합니다').check()
  await page.getByRole('button', { name: '결제하기', exact: true }).click()
  await expect(page.getByRole('heading', { name: '통합 결제', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '통합 결제하기', exact: true }).click()
  await expect(page.getByText('통합 결제가 완료되었어요', { exact: true })).toBeVisible({ timeout: 30000 })
  const number = new URL(page.url()).pathname.split('/').pop()!
  const saved = await request.get(`/api/commerce/v1/payment-groups/${number}`, { headers: await bearer(request, 'user') })
  const group = await saved.json(); expect(group.orders).toHaveLength(1)
  const order = group.orders[0]; expect(order.productName).toBe(f.name); expect(order.quantity).toBe(1); expect(order.totalAmount).toBe(10000)
})

test('kind: USER cannot enter seller console; seller can revoke their own sessions', async ({ page, request }) => {
  await page.goto('/admin/products')
  await page.getByLabel('아이디 또는 이메일').fill('user'); await page.getByLabel('비밀번호', { exact: true }).fill('user')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByText('판매자만 접근할 수 있어요.', { exact: true })).toBeVisible()
  const user = await bearer(request, 'user')
  expect((await request.get('/api/shopping/v1/admin/products', { headers: user })).status()).toBe(403)
  await login(page, 'seller')
  const seller = await bearer(request)
  await page.getByRole('link', { name: '← 쇼핑몰로' }).click(); await page.getByRole('link', { name: '내 계정', exact: true }).click()
  await page.getByRole('button', { name: '내 모든 세션 종료' }).click()
  await expect(page.getByRole('heading', { name: '로그인', exact: true })).toBeVisible()
  expect((await request.get('/api/member/v1/members/me', { headers: seller })).status()).toBe(401)
})

test('kind: cart removal deletes only the selected member item', async ({ page, request }) => {
  const f = await fixture(request)
  await login(page); await page.getByRole('link', { name: '쇼핑', exact: true }).click()
  await page.getByRole('link', { name: new RegExp(f.name) }).first().click()
  await page.getByRole('button', { name: '장바구니 담기', exact: true }).click(); await expect(page.getByText('장바구니에 담았어요.', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '장바구니', exact: true }).click()
  const row = page.locator('section').filter({ has: page.getByRole('heading', { name: f.name, exact: true }) })
  await row.getByRole('button', { name: '삭제', exact: true }).click(); await expect(row).toHaveCount(0)
  const saved = await request.get('/api/commerce/v1/cart/items', { headers: await bearer(request, 'user') })
  expect((await saved.json()).some((item: { productId: number }) => item.productId === Number(f.productId))).toBeFalsy()
})

test('kind: reload restores verified login and logout prevents restoration', async ({ page }) => {
  await login(page)
  await page.reload(); await expect(page.getByRole('heading', { name: '내 계정', exact: true })).toBeVisible()
  await page.goto('/orders/lookup'); await expect(page.getByRole('heading', { name: '내 주문', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await page.reload(); await expect(page.getByRole('heading', { name: '로그인', exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.keys(sessionStorage).some(key => key.startsWith('shoppinglive:refresh:')))).toBeFalsy()
  await page.goto('/cart'); await expect(page.getByRole('heading', { name: '로그인', exact: true })).toBeVisible()
})
